[package]
name = "icepeak-db"
version = "0.1.0"
edition = "2021"

[dependencies]
icepeak-kv = { path = "../icepeak-kv/" }

bytes = { workspace = true }
smol_str = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
