[workspace]
members = ["icepeak-kv", "icepeak-db"]

[workspace.dependencies]
smol_str = "0.3.1"
parking_lot = "0.12.3"
thiserror = "1.0.61"
tokio = { version = "1.40.0", features = ["rt-multi-thread", "time", "macros"] }
tokio-util = "0.7.12"
chrono = "0.4.38"
rand = "0.8.5"
