[package]
name = "icepeak-kv"
version = "0.1.0"
edition = "2021"

[dependencies]
parking_lot = { workspace = true }
smol_str = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
chrono = { workspace = true }
